In [1]:
pip install requests

Requirement already satisfied: requests in /opt/conda/lib/python3.8/site-packages (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/conda/lib/python3.8/site-packages (from requests) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.8/site-packages (from requests) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.8/site-packages (from requests) (1.26.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import json
import requests

## Import

In [4]:
fb = pd.read_csv('football.csv')
fb

                   name
0            Chelsea FC
1            Arsenal FC
2            Everton FC
3  Manchester United FC
4    Manchester City FC
5        Aston Villa FC
6             Fulham FC
7          Liverpool FC
8        Southampton FC
9  Tottenham Hotspur FC

In [5]:
import requests

url = "https://premier-league-standings1.p.rapidapi.com/"

headers = {
	"X-RapidAPI-Key": "ed3284ad15msh9c0872c017bc266p139ab2jsn355a61eec44a",
	"X-RapidAPI-Host": "premier-league-standings1.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

In [6]:
data = response.json()

In [7]:
df = pd.json_normalize(data)
df

,team.name,team.logo,team.abbreviation,stats.wins,stats.losses,stats.ties,stats.gamesPlayed,stats.goalsFor,stats.goalsAgainst,stats.points,stats.rank,stats.goalDifference
0,Arsenal,https://a.espncdn.com/i/teamlogos/soccer/500/3...,ARS,9,1,1,11,25,11,28,1,14
1,Manchester City,https://a.espncdn.com/i/teamlogos/soccer/500/3...,MNC,8,1,2,11,36,11,26,2,25
2,Tottenham Hotspur,https://a.espncdn.com/i/teamlogos/soccer/500/3...,TOT,7,3,2,12,23,14,23,3,9
3,Newcastle United,https://a.espncdn.com/i/teamlogos/soccer/500/3...,NEW,5,1,6,12,20,10,21,4,10
4,Chelsea,https://a.espncdn.com/i/teamlogos/soccer/500/3...,CHE,6,2,3,11,16,11,21,5,5
5,Manchester United,https://a.espncdn.com/i/teamlogos/soccer/500/3...,MAN,6,3,2,11,16,16,20,6,0
6,Fulham,https://a.espncdn.com/i/teamlogos/soccer/500/3...,FUL,5,4,3,12,22,22,18,7,0
7,Liverpool,https://a.espncdn.com/i/teamlogos/soccer/500/3...,LIV,4,3,4,11,22,13,16,8,9
8,Brighton & Hove Albion,https://a.espncdn.com/i/teamlogos/soccer/500/3...,BHA,4,4,3,11,15,14,15,9,1
9,West Ham United,https://a.espncdn.com/i/teamlogos/soccer/500/3...,WHU,4,6,2,12,11,12,14,10,-1
10,Brentford,https://a.espncdn.com/i/teamlogos/soccer/500/3...,BRE,3,4,5,12,18,21,14,11,-3
11,Everton,https://a.espncdn.com/i/teamlogos/soccer/500/3...,EVE,3,5,4,12,11,12,13,12,-1
12,Crystal Palace,https://a.espncdn.com/i/teamlogos/soccer/500/3...,CRY,3,4,4,11,12,16,13,13,-4
13,AFC Bournemouth,https://a.espncdn.com/i/teamlogos/soccer/500/3...,BOU,3,5,4,12,10,25,13,14,-15
14,Aston Villa,https://a.espncdn.com/i/teamlogos/soccer/500/3...,AVL,3,6,3,12,11,16,12,15,-5
15,Southampton,https://a.espncdn.com/i/teamlogos/soccer/500/3...,SOU,3,6,3,12,11,19,12,16,-8
16,Leicester City,https://a.espncdn.com/i/teamlogos/soccer/500/3...,LEI,3,7,2,12,21,24,11,17,-3
17,Leeds United,https://a.espncdn.com/i/teamlogos/soccer/500/3...,LEE,2,6,3,11,13,18,9,18,-5
18,Wolverhampton Wanderers,https://a.espncdn.com/i/teamlogos/soccer/500/3...,WOL,2,7,3,12,5,18,9,19,-13
19,Nottingham Forest,https://a.espncdn.com/i/teamlogos/soccer/500/3...,FOR,2,7,3,12,8,23,9,20,-15